version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"                  # Location of go.mod
    schedule:
      interval: "weekly"            # Can also be "daily" or "monthly"
    commit-message:
      prefix: "deps(go)"
    open-pull-requests-limit: 5

  - package-ecosystem: "docker"
    directory: "/"                  # Location of Dockerfile
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(docker)"
    open-pull-requests-limit: 5
