services:
  telegram-bot:
    build: .
    container_name: telegram-bot
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - MODERATION_GROUP_ID=${MODERATION_GROUP_ID}
      - APPROVED_GROUP_ID=${APPROVED_GROUP_ID}
      - TIMEOUT_MINUTES=${TIMEOUT_MINUTES}
      - LANG=${LANG}
    volumes:
      - ./data:/app/data
    restart: unless-stopped
